type: workflow
name: secret_scan
alias: secret
description: Secret Scan in codebases
tags: [vuln, code]
input_types:
  - path
tasks:
  trufflehog:
    description: Run secret scan
  gitleaks:
    description: Run secret scan