name: test_fuzz
type: workflow
description: Test fuzzing
long_description: |
  Test fuzzing
tags: [fuzz]
input_types:
  - url
  - host

tasks:
  httpx:
    description: Test HTTP probing
  ffuf:
    description: Test fuzzing
    targets_:
      - type: url
        field: '{protocol}://FUZZ.{host}'
