type: profile
name: active
description: "Active only (requests to targets)"
enforce: true
opts:
  active: True
  domain_recon_active: True
  subdomain_recon_active: True
  host_recon_active: True
  url_crawl_active: True
  url_vuln_active: True
