type: profile
name: hunt_secrets
category: content
description: "Hunt for secrets and other interesting content in HTTP responses"
enforce: true
opts:
    hunt_secrets: true
    subdomain_recon_hunt_secrets: true
    url_crawl_hunt_secrets: true
    url_dirsearch_hunt_secrets: true
    url_fuzz_hunt_secrets: true
    url_params_fuzz_hunt_secrets: true
